//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class AdvisingDBEntities : DbContext
{
    public AdvisingDBEntities()
        : base("name=AdvisingDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<AdvisorTable> AdvisorTables { get; set; }
    public virtual DbSet<AppointmentTable> AppointmentTables { get; set; }
    public virtual DbSet<CarTable> CarTables { get; set; }
    public virtual DbSet<EmailTable> EmailTables { get; set; }
    public virtual DbSet<StudentTable> StudentTables { get; set; }
    public virtual DbSet<UserTable> UserTables { get; set; }
}
